### ISSUE TITLE
CSS for Printing

### ISSUE THREAD

**Issue by alexclst** [tenseg/subcaucus-calculator#46]
We should create a decent view that is used when trying to print the main page. Right now we do nothing specific when printing. We should make a cleaner view in CSS `@media print` that hides much of the app elements around the main table, and presents the meeting name, delegates allowed, and subcaucus information in a clear, printer-friendly, fashion.

When printing, we should consider if showing the app version number in the footer area is a good idea. We definitely should do that if we add the app version number to email, text, and CSV exports, as discussed in #43. But this would be one element which we do not show normally, but instead show just when printing.

**Comment by efc** [comment]
Good idea, Alex! I think it's ok to show the app version even when on screen, but I'll make it low-contrast so it is not too distracting. In print, I'll up the contrast.
